[tools]
rust = "1.95.0"

[tasks.dev]
description = "Debug build"
run = "cargo build"

[tasks.build]
description = "Build optimised release binary for your CPU"
alias = "b"
run = 'RUSTFLAGS="-C target-cpu=native" cargo build --release'

[tasks.start]
description = "Run the optimized binary"
run = "cargo run --release -- view ../public/cat.png"
